//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Undersoft.Picatch.Agent
{
    using System;
    using System.Collections.Generic;
    
    public partial class bufor
    {
        public int id { get; set; }
        public Nullable<int> dokid { get; set; }
        public string kod { get; set; }
        public string nazwa { get; set; }
        public string cenazk { get; set; }
        public Nullable<decimal> ilosc { get; set; }
        public string stan { get; set; }
        public string cenasp { get; set; }
        public string vat { get; set; }
    }
}
