//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Undersoft.Picatch.Agent
{
    using System;
    using System.Collections.Generic;
    
    public partial class dok
    {
        public int id { get; set; }
        public string nazwadok { get; set; }
        public string typ { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string device { get; set; }
    }
}
