//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Undersoft.Picatch.Agent
{
    using System;
    using System.Collections.Generic;
    
    public partial class ediend
    {
        public int id { get; set; }
        public string NrDok { get; set; }
        public string Vat { get; set; }
        public string SumaNet { get; set; }
        public string SumaVat { get; set; }
        public string status { get; set; }
        public Nullable<bool> complete { get; set; }
    }
}
