//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Undersoft.Picatch.Agent
{
    using System;
    using System.Collections.Generic;
    
    public partial class edihead
    {
        public int id { get; set; }
        public string FileName { get; set; }
        public string TypPolskichLiter { get; set; }
        public string TypDok { get; set; }
        public string NrDok { get; set; }
        public string Data { get; set; }
        public string DataRealizacji { get; set; }
        public string Magazyn { get; set; }
        public string SposobPlatn { get; set; }
        public string TerminPlatn { get; set; }
        public string IndeksCentralny { get; set; }
        public string NazwaWystawcy { get; set; }
        public string AdresWystawcy { get; set; }
        public string KodWystawcy { get; set; }
        public string MiastoWystawcy { get; set; }
        public string UlicaWystawcy { get; set; }
        public string NIPWystawcy { get; set; }
        public string BankWystawcy { get; set; }
        public string KontoWystawcy { get; set; }
        public string TelefonWystawcy { get; set; }
        public string NrWystawcyWSieciSklepow { get; set; }
        public string NazwaOdbiorcy { get; set; }
        public string AdresOdbiorcy { get; set; }
        public string KodOdbiorcy { get; set; }
        public string MiastoOdbiorcy { get; set; }
        public string UlicaOdbiorcy { get; set; }
        public string NIPOdbiorcy { get; set; }
        public string BankOdbiorcy { get; set; }
        public string KontoOdbiorcy { get; set; }
        public string TelefonOdbiorcy { get; set; }
        public string NrOdbiorcyWSieciSklepow { get; set; }
        public string DoZaplaty { get; set; }
        public string status { get; set; }
        public Nullable<bool> complete { get; set; }
    }
}
