//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Undersoft.Picatch.Agent
{
    using System;
    using System.Collections.Generic;
    
    public partial class fedibody
    {
        public int id { get; set; }
        public string NrDok { get; set; }
        public string Nazwa { get; set; }
        public string kod { get; set; }
        public string Vat { get; set; }
        public string Jm { get; set; }
        public string Asortyment { get; set; }
        public string Sww { get; set; }
        public string PKWiU { get; set; }
        public string Ilosc { get; set; }
        public string Cena { get; set; }
        public string Wartosc { get; set; }
        public string IleWOpak { get; set; }
        public string CenaSp { get; set; }
        public string status { get; set; }
        public Nullable<bool> complete { get; set; }
    }
}
