//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Undersoft.Picatch.Agent
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Undersoft.Picatch.Agent.DB;
    
    public partial class BazaEntities : DbContext
    {
        public BazaEntities()
            : base("name=BazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bufor> bufor { get; set; }
        public DbSet<dok> dok { get; set; }
        public DbSet<edibody> edibody { get; set; }
        public DbSet<ediend> ediend { get; set; }
        public DbSet<edihead> edihead { get; set; }
        public DbSet<fedibody> fedibody { get; set; }
        public DbSet<fediend> fediend { get; set; }
        public DbSet<fedihead> fedihead { get; set; }
        public DbSet<magazyn> magazyn { get; set; }
        public DbSet<opcje> opcje { get; set; }
        public DbSet<stany> stany { get; set; }
    }
}
