//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Undersoft.Picatch.Agent
{
    using System;
    using System.Collections.Generic;
    
    public partial class opcje
    {
        public int id { get; set; }
        public string transfer { get; set; }
        public string com { get; set; }
        public string ip { get; set; }
        public string ufile { get; set; }
        public string dfile { get; set; }
        public string bdll { get; set; }
        public Nullable<bool> bflag { get; set; }
        public Nullable<bool> ipflag { get; set; }
        public Nullable<int> port { get; set; }
        public string skaner { get; set; }
        public string serverpcm { get; set; }
        public string loginpcm { get; set; }
        public string passwdpcm { get; set; }
        public string bazapcm { get; set; }
    }
}
