//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Undersoft.Picatch.Agent
{
    using System;
    using System.Collections.Generic;
    
    public partial class stany
    {
        public int id { get; set; }
        public string kod { get; set; }
        public Nullable<decimal> stan { get; set; }
        public Nullable<int> MagId { get; set; }
        public string Nazwa { get; set; }
    }
}
